Fix a missing dependency of libmesa_intel_compiler
To fix errors like:

 build/core/binary.mk:620: recipe for target 'out/target/product/x86_64/obj/STATIC_LIBRARIES/libmesa_intel_compiler_intermediates/compiler/brw_fs_cmod_propagation.o' failed
 make: *** [out/target/product/x86_64/obj/STATIC_LIBRARIES/libmesa_intel_compiler_intermediates/compiler/brw_fs_cmod_propagation.o] Error 1
 In file included from external/mesa/src/intel/compiler/brw_fs_copy_propagation.cpp:38:
 In file included from external/mesa/src/intel/compiler/brw_fs.h:31:
 In file included from external/mesa/src/intel/compiler/brw_shader.h:32:
 external/mesa/src/compiler/nir/nir.h:48:10: fatal error: 'nir_opcodes.h' file not found
 #include "nir_opcodes.h"
          ^
 In file included from external/mesa/src/intel/compiler/brw_fs_combine_constants.cpp:37:
 In file included from external/mesa/src/intel/compiler/brw_fs.h:31:
 In file included from external/mesa/src/intel/compiler/brw_shader.h:32:
 external/mesa/src/compiler/nir/nir.h:48:10: fatal error: 'nir_opcodes.h' file not found
 #include "nir_opcodes.h"
          ^
 1 error generated.

On the other hand, libmesa_intel_compiler doesn't need libmesa_genxml.
So drop it.