Fix a missing dependency in libmesa_i965_gen*
To fix errors like:

 In file included from external/mesa/src/mesa/drivers/dri/i965/genX_blorp_exec.c:33:
 In file included from external/mesa/src/intel/blorp/blorp_genX_exec.h:111:
 external/mesa/src/intel/genxml/genX_pack.h:32:12: fatal error: 'genxml/gen4_pack.h' file not found
 #  include "genxml/gen4_pack.h"
            ^
 1 error generated.
 build/core/binary.mk:700: recipe for target 'out/target/product/x86_64/obj_x86/STATIC_LIBRARIES/libmesa_i965_gen4_intermediates/genX_blorp_exec.o' failed